title: "Aesthetic Physique Program"
description: "Build your best physique step-by-step"

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "default" # options: dark, default, dark, neon, etc.

markdown: kramdown
