remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme

# Site Settings
title: "Aesthetic Physique Bootcamp"
description: "Build your best physique step-by-step"

# 🌅 Skin
minimal_mistakes_skin: "contrast" # options: dark, default, dark, neon, etc.

# Optional (nice defaults)
markdown: kramdown
permalink: pretty

# Navigation (edit as needed)
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Contact"
    url: /contact/
